### ISSUE TITLE
connection could not be established with host smtp.qq.com

### ISSUE THREAD

**Issue by FupingQiu** [FupingQiu/okrsw#21]
connection could not be established with host smtp.qq.com [Unable to find the socket transport "test" - did you forget to enable it when you configured PHP? #-2092507384]
E:\laragon40\www\OKRsing\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php#269

[2019-09-19 22:32:38] local.ERROR: Connection could not be established with host smtp.qq.com [php_network_getaddresses: getaddrinfo failed: ??֪???????????  #0]  
[2019-09-19 22:32:38] local.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at E:\\laragon40\\www\\OKRsing\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\JsonResponse.php:75)
[stacktrace]
#0 E:\\laragon40\\www\\OKRsing\\vendor\\symfony\\http-foundation\\JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)

[2019-09-19 22:59:26] local.ERROR: Expected response code 220 but got an empty response {"exception":"[object] (Swift_TransportException(code: 0): Expected response code 220 but got an empty response at E:\\laragon40\\www\\OKRsing\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php:445)
[stacktrace]
#0 E:\\laragon40\\www\\OKRsing\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(358): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array)
#1 E:\\laragon40\\www\\OKRsing\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(147): Swift_Transport_AbstractSmtpTransport->readGreeting()
#2 E:\\laragon40\\www\\OKRsing\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 E:\\laragon40\\www\\OKRsing\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailer.php(484): Swift_Mailer->send(Object(Swift_Message), Array)
#4 E:\\laragon40\\www\\OKRsing\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailer.php(259): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 E:\\laragon40\\www\\OKRsing\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\Channels\\MailChannel.ph

**Comment by FupingQiu** [comment]
Expected response code 220 but got an empty response {"exception":"[object] (Swift_TransportException(code: 0) 
这个是因为MAIL_PORT设置问题引起，smtp.qq.com的端口为465
